### ISSUE TITLE
PGN output bug?

### ISSUE THREAD

**Issue by kenpchess** [nguyenpham/Banksia#4]
BTW, thanks for the Mac binaries! I noticed a strange PGN output bug. It appears the first move reply is not written into the PGN file? For example:

[Event 	"Computer event"]
[Site 	"Somewhere on Earth"]
[Date 	"2019.07.14"]
[Round 	"1"]
[White 	"Stockfish 291118 64"]
[Black 	"Texel 1.08a11"]
[Result 	"1-0"]
[TimeControl 	"40/6:0.5"]
[Time 	"11:12:29"]
[Board 	"2"]
[Termination 	"mate"]
1. e4 2. d5 xd5 3. Nf6 Nf3 4. Nxd5 d4 5. e6
c4 6. Nf6 Nc3 7. c5 Bf4 8. Be7 d5 9. Bd6
Bxd6 10. Qxd6 Nb5 11. Qb6 d6 12. Na6 Be2 13. Bd7
a4 14. Bxb5 cxb5 15. Nb8 a5 16. Qd8 Ne5 17. Nd5
Nc4 18. Nd7 O-O 19. O-O Bf3 20. Qg5 g3 21. N7f6
Re1 22. Qh6 Re5 23. Rfe8 h4 24. g6 Kg2 25. Qg7
Rc1 26. Rad8 Qd2 27. b6 h5 28. xa5 xg6 29. hxg6
Qxa5 30. Rb8 Ree1 31. Red8 Rh1 32. Nd7 b3 33. Ne5
Be4 34. Nd7 Rh2 35. N7f6 Bf3 36. Rd7 Rch1 37. Nh5
Qd2 38. Ndf6 g4 39. Rxb5 xh5 40. xh5+ Kf1 41. Rxb3
Qd1 42. Rxf3 Qxf3 43. Rd8 Rg1 44. Ng4 Rxh5 45. Qa1+
Kg2 46. Qg7 Kh1 47. f5 Qf4 48. Rd7 Rg5 49. Kh8
Rxg7 50. Rxg7 Re1 51. Nxf2+ Qxf2 52. Rh7+ Kg2 53. Rg7+
Kf1 54. Kg8 Rxe6 55. Rg5 Qh4 56. Rg4 Re8+ 57. Kg7
Re7+ 58. Kg8 Qh7+ 59. Kf8 Qf7+ 1-0

[Event 	"Computer event"]
[Site 	"Somewhere on Earth"]
[Date 	"2019.07.14"]
[Round 	"1"]
[White 	"Texel 1.08a11"]
[Black 	"Stockfish 291118 64"]
[Result 	"0-1"]
[TimeControl 	"40/6:0.5"]
[Time 	"11:12:41"]
[Board 	"1"]
[Termination 	"mate"]
1. e4 2. e5 Nf3 3. Nf6 d4 4. Nxe4 Bd3 5. d5
Nxe5 6. Nd7 O-O 7. Nxe5 xe5 8. Nc5 Be2 9. c6
c4 10. d4 b4 11. d3 xc5 12. xe2 Qxe2 13. Qd4
Bb2 14. Bg4 Bxd4 15. Bxe2 Rc1 16. O-O-O Be3 17. Be7
Nd2 18. Bd3 h3 19. Bg6 a3 20. Rd3 Nf3 21. h6
a4 22. Rhd8 Ne1 23. Rb3 a5 24. a6 Kh2 25. Rb2
Nf3 26. Be4 Kg3 27. f5 Rd1 28. g5 Kh2 29. Bxf3
xf3 30. f4 Bd4 31. Rc2 e6 32. Rxc4 Be5 33. Rxc5
Rxd8+ 34. Kxd8 Bd4 35. Rf5 Kg2 36. Bb4 Rb1 37. c5
Rb3 38. Bxa5 Ba1 39. b6 Rd3+ 40. Ke7 Rd7+ 41. Kxe6
Rh7 42. c4 Rxh6+ 43. Kd5 h4 44. xh4 Kh3 45. c3
Kxh4 46. c2 Bb2 47. Bc3 Bc1 48. Rf6 Rh7 49. b5
Kg5 50. Rf8 Rd7+ 51. Kc6 Ra7 52. Kb6 Rh7 53. b4
Rh6+ 54. Kb5 Rh7 55. Kc4 Rc7+ 56. Kd3 Rc6 57. a5
Kg4 58. a4 Ra6 59. Ke2 Rxa4 60. Kd1 Bxf4 61. Rxf4+
Kxf4 62. c1=Q+ Kg4 63. b3 Kg3 64. b2 f4 65. b1=Q
Kf3 66. Kd2 Ra2+ 67. Qxa2 f5 68. Qg1 Ke4 69. Qxf2
f6 70. Qc4+ 0-1

Notice there is no reply to move 1 in both games!

Thanks, project looking good!

**Comment by nguyenpham** [comment]
Thanks for the report. It is a bug and fixed in the new release 2.22.
