### ISSUE TITLE
Banksia implementing engines playing chess variants, musketeer stockfish

### ISSUE THREAD

**Issue by musketeerchess** [nguyenpham/Banksia#9]
I’m Dr Haddad, chess fun and inventor of many chess variants.

Take a look at www.musketeerchess.net

This is an offer for the programmers.

My goal is the following:

Organise an annual [to begin] Tournament using winboard or another UCI compatible GUI.

The tournament should involve a minimum of 6 different engines. 

Source code must be provided to avoid clones, the only participant with stockfish musketeer is @ianfab or @ddugovich in the official tournament but clones can compete for other prices, the clone should be identifiable and changes from original engine explained clearly.

Winner 1500$
2nd 1000$
3d 500$ 

Each participant with working engine without easily identifiable bugs 200$

The methodology to gate choice of the additional pieces etc should be agreed between programmers when we decide beginning of the tournament. Naturally i will be involved in this.

PRICES Payment method Paypal.

Additional 750$ for the programmer that can provide a GUI newly developed and that can use classic stockfish and musketeer stockfish.

My mail: musketeerchess (a) gmail.com

**Comment by nguyenpham** [comment]
Thanks for the info. Banksia plays as a chess interface but not a chess engine. Thus it won't participate in the tournament. We don't support widely chess variants in the coming time since want to focus on only few basic variants such as chess/chess960.  I closed this issue and may re-open it when we can start.
